In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
b=np.array([[7,8,9],[4,5,6],[1,2,3]])
print(a-b)

[[-6 -6 -6]
 [ 0  0  0]
 [ 6  6  6]]


In [4]:
c=np.array([1,2,3])
print(np.dot(a,c))

[14 32 50]
