In [41]:
import tensorflow as tf

In [42]:
from numpy.random import RandomState

In [43]:
batch_size=8

In [44]:
interactive_sesssion=tf.InteractiveSession()

In [45]:
x=tf.placeholder(tf.float32,shape=(None,2),name='x-input')

In [46]:
y_=tf.placeholder(tf.float32,shape=(None,1),name='y-input')

In [47]:
w1=tf.Variable(tf.random_normal([2,1],stddev=1,seed=1))

In [48]:
y=tf.matmul(x,w1)

In [49]:
loss_less=10

In [50]:
loss_more=1

In [51]:
loss_=tf.where(tf.greater(y,y_),
                        (y-y_)*loss_more,
                        (y_-y)*loss_less)

In [52]:
loss=tf.reduce_sum(loss_)

In [53]:
train_step=tf.train.AdamOptimizer(0.001).minimize(loss)

In [54]:
rdm=RandomState(1)

In [55]:
dataset=128

In [56]:
X=rdm.rand(dataset,2)

In [57]:
Y=[[x1 + x2 + rdm.rand()/10.0+0.5] for (x1,x2) in X]

In [58]:
init_op=tf.initialize_all_variables()

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [59]:
interactive_sesssion.run(init_op)

In [60]:
for i in range(300):
    start=(i*batch_size)%dataset
    end=min(start+batch_size,dataset)
    interactive_sesssion.run(train_step,feed_dict={x:X[start:end],y_:Y[start:end]})
    print(interactive_sesssion.run(w1))
    #print(interactive_sesssion.run(loss))

[[-0.81031823]
 [ 1.4855988 ]]
[[-0.80933279]
 [ 1.48660016]]
[[-0.80836678]
 [ 1.48760271]]
[[-0.80739707]
 [ 1.48857152]]
[[-0.80641365]
 [ 1.4895432 ]]
[[-0.80542254]
 [ 1.4905293 ]]
[[-0.80442679]
 [ 1.49152255]]
[[-0.8034274 ]
 [ 1.49251425]]
[[-0.80242074]
 [ 1.4934833 ]]
[[-0.80143076]
 [ 1.49445653]]
[[-0.80044913]
 [ 1.4954375 ]]
[[-0.79947007]
 [ 1.49640727]]
[[-0.7984708 ]
 [ 1.49739242]]
[[-0.79748935]
 [ 1.49838436]]
[[-0.79650176]
 [ 1.49939191]]
[[-0.79551846]
 [ 1.50041449]]
[[-0.79457343]
 [ 1.50143099]]
[[-0.79363602]
 [ 1.50244796]]
[[-0.79267466]
 [ 1.50346613]]
[[-0.79172212]
 [ 1.50445485]]
[[-0.79074574]
 [ 1.50543559]]
[[-0.7897619 ]
 [ 1.50643003]]
[[-0.7887727 ]
 [ 1.50742984]]
[[-0.78777856]
 [ 1.50842512]]
[[-0.78677291]
 [ 1.50939476]]
[[-0.78578454]
 [ 1.51036429]]
[[-0.78480619]
 [ 1.51133919]]
[[-0.78383213]
 [ 1.51229906]]
[[-0.78283054]
 [ 1.51327527]]
[[-0.78184843]
 [ 1.51425779]]
[[-0.78085971]
 [ 1.51525998]]
[[-0.77987641]
 [ 1.51628256]]
[[-0.778