In [14]:
import tensorflow as tf

In [15]:
from numpy.random import RandomState

In [16]:
batch_size=8

In [17]:
interactive_sesssion=tf.InteractiveSession()

In [18]:
x=tf.placeholder(tf.float32,shape=(None,2),name='x-input')

In [19]:
y_=tf.placeholder(tf.float32,shape=(None,1),name='y-input')

In [20]:
w1=tf.Variable(tf.random_normal([2,1],stddev=1,seed=1))

In [21]:
y=tf.matmul(x,w1)

In [22]:
loss_less=10

In [23]:
loss_more=1

In [24]:
loss_=tf.where(tf.greater(y,y_),
                        (y-y_)*loss_more,
                        (y_-y)*loss_less)

In [25]:
loss=tf.reduce_sum(loss_)

In [26]:
train_step=tf.train.AdamOptimizer(0.001).minimize(loss)

In [27]:
rdm=RandomState(1)

In [28]:
dataset=128

In [29]:
X=rdm.rand(dataset,2)

In [30]:
Y=[[x1 + x2 + rdm.rand()/10.0+0.5] for (x1,x2) in X]

In [31]:
init_op=tf.initialize_all_variables()

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [32]:
interactive_sesssion.run(init_op)

In [39]:
for i in range(300):
    start=(i*batch_size)%dataset
    end=min(start+batch_size,dataset)
    interactive_sesssion.run(train_step,feed_dict={x:X[start:end],y_:Y[start:end]})
    print(interactive_sesssion.run(w1))
    #print(interactive_sesssion.run(loss_))

[[-0.80931824]
 [ 1.48659885]]
[[-0.80832839]
 [ 1.48760116]]
[[-0.80736315]
 [ 1.48860526]]
[[-0.80639023]
 [ 1.48957849]]
[[-0.80540425]
 [ 1.49055254]]
[[-0.80440873]
 [ 1.49154079]]
[[-0.80340689]
 [ 1.49253595]]
[[-0.80240017]
 [ 1.49352932]]
[[-0.80138522]
 [ 1.49450004]]
[[-0.80038571]
 [ 1.49547446]]
[[-0.79939383]
 [ 1.49645627]]
[[-0.7984041 ]
 [ 1.49742663]]
[[-0.79739398]
 [ 1.49841249]]
[[-0.79640138]
 [ 1.49940503]]
[[-0.79540247]
 [ 1.50041366]]
[[-0.79440778]
 [ 1.50143766]]
[[-0.79345149]
 [ 1.50245571]]
[[-0.79250294]
 [ 1.50347435]]
[[-0.79153037]
 [ 1.50449419]]
[[-0.79056674]
 [ 1.50548446]]
[[-0.78957921]
 [ 1.50646663]]
[[-0.78858423]
 [ 1.5074625 ]]
[[-0.78758401]
 [ 1.50846374]]
[[-0.78657889]
 [ 1.50946045]]
[[-0.78556228]
 [ 1.51043129]]
[[-0.7845633 ]
 [ 1.51140201]]
[[-0.78357458]
 [ 1.51237798]]
[[-0.78259039]
 [ 1.5133388 ]]
[[-0.78157848]
 [ 1.51431596]]
[[-0.78058642]
 [ 1.51529944]]
[[-0.77958786]
 [ 1.51630282]]
[[-0.77859491]
 [ 1.51732671]]
[[-0.777