In [25]:
import tensorflow as tf

In [26]:
interactive_session=tf.InteractiveSession()

In [27]:
x=tf.constant([[3.0,4.0]])

In [28]:
y_=tf.constant([16.0])

In [29]:
w=tf.Variable([[100.0],[80.0]])

In [30]:
y=tf.matmul(x,w)

In [31]:
loss=tf.abs(tf.reduce_mean(y-y_))

In [37]:
optim = tf.train.GradientDescentOptimizer(0.05)
#help(tf.train.AdamOptimizer)

Help on class AdamOptimizer in module tensorflow.python.training.adam:

class AdamOptimizer(tensorflow.python.training.optimizer.Optimizer)
 |  Optimizer that implements the Adam algorithm.
 |  
 |  See [Kingma et. al., 2014](http://arxiv.org/abs/1412.6980)
 |  ([pdf](http://arxiv.org/pdf/1412.6980.pdf)).
 |  
 |  Method resolution order:
 |      AdamOptimizer
 |      tensorflow.python.training.optimizer.Optimizer
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, learning_rate=0.001, beta1=0.9, beta2=0.999, epsilon=1e-08, use_locking=False, name='Adam')
 |      Construct a new Adam optimizer.
 |      
 |      Initialization:
 |      
 |      ```
 |      m_0 <- 0 (Initialize initial 1st moment vector)
 |      v_0 <- 0 (Initialize initial 2nd moment vector)
 |      t <- 0 (Initialize timestep)
 |      ```
 |      
 |      The update rule for `variable` with gradient `g` uses an optimization
 |      described at the end of section2 of the paper:
 |      
 |   

In [33]:
train_step=optim.minimize(loss)

In [34]:
init_op=tf.initialize_all_variables()

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [35]:
interactive_session.run(init_op)

In [36]:
for i in range(500):
    interactive_session.run(train_step)
    l=interactive_session.run(loss)
    weight=interactive_session.run(w)
    yy=interactive_session.run(y)
    print(weight)
    print(l)
    print(yy)

[[ 99.84999847]
 [ 79.80000305]]
602.75
[[ 618.75]]
[[ 99.69999695]
 [ 79.6000061 ]]
601.5
[[ 617.5]]
[[ 99.54999542]
 [ 79.40000916]]
600.25
[[ 616.25]]
[[ 99.3999939 ]
 [ 79.20001221]]
599.0
[[ 615.]]
[[ 99.24999237]
 [ 79.00001526]]
597.75
[[ 613.75]]
[[ 99.09999084]
 [ 78.80001831]]
596.5
[[ 612.50006104]]
[[ 98.94998932]
 [ 78.60002136]]
595.25
[[ 611.25006104]]
[[ 98.79998779]
 [ 78.40002441]]
594.0
[[ 610.00006104]]
[[ 98.64998627]
 [ 78.20002747]]
592.75
[[ 608.75006104]]
[[ 98.49998474]
 [ 78.00003052]]
591.5
[[ 607.50006104]]
[[ 98.34998322]
 [ 77.80003357]]
590.25
[[ 606.25012207]]
[[ 98.19998169]
 [ 77.60003662]]
589.0
[[ 605.00012207]]
[[ 98.04998016]
 [ 77.40003967]]
587.75
[[ 603.75012207]]
[[ 97.89997864]
 [ 77.20004272]]
586.5
[[ 602.50012207]]
[[ 97.74997711]
 [ 77.00004578]]
585.25
[[ 601.25012207]]
[[ 97.59997559]
 [ 76.80004883]]
584.0
[[ 600.00012207]]
[[ 97.44997406]
 [ 76.60005188]]
582.75
[[ 598.75012207]]
[[ 97.29997253]
 [ 76.40005493]]
581.5
[[ 597.50012207]