In [38]:
import tensorflow as tf

In [39]:
interactive_session=tf.InteractiveSession()

In [40]:
x=tf.constant([[3.0,4.0]])

In [41]:
y_=tf.constant([16.0])

In [42]:
w=tf.Variable([[100.0],[80.0]])

In [43]:
y=tf.matmul(x,w)

In [44]:
loss=tf.abs(tf.reduce_mean(y-y_))

In [45]:
optim = tf.train.GradientDescentOptimizer(5)

In [46]:
train_step=optim.minimize(loss)

In [47]:
init_op=tf.initialize_all_variables()

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [48]:
interactive_session.run(init_op)

In [49]:
for i in range(100):
    interactive_session.run(train_step)
    l=interactive_session.run(loss)
    weight=interactive_session.run(w)
    yy=interactive_session.run(y)
    print(weight)
    print(l)
    print(yy)

[[ 85.]
 [ 60.]]
479.0
[[ 495.]]
[[ 70.]
 [ 40.]]
354.0
[[ 370.]]
[[ 55.]
 [ 20.]]
229.0
[[ 245.]]
[[ 40.]
 [  0.]]
104.0
[[ 120.]]
[[ 25.]
 [-20.]]
21.0
[[-5.]]
[[ 40.]
 [  0.]]
104.0
[[ 120.]]
[[ 25.]
 [-20.]]
21.0
[[-5.]]
[[ 40.]
 [  0.]]
104.0
[[ 120.]]
[[ 25.]
 [-20.]]
21.0
[[-5.]]
[[ 40.]
 [  0.]]
104.0
[[ 120.]]
[[ 25.]
 [-20.]]
21.0
[[-5.]]
[[ 40.]
 [  0.]]
104.0
[[ 120.]]
[[ 25.]
 [-20.]]
21.0
[[-5.]]
[[ 40.]
 [  0.]]
104.0
[[ 120.]]
[[ 25.]
 [-20.]]
21.0
[[-5.]]
[[ 40.]
 [  0.]]
104.0
[[ 120.]]
[[ 25.]
 [-20.]]
21.0
[[-5.]]
[[ 40.]
 [  0.]]
104.0
[[ 120.]]
[[ 25.]
 [-20.]]
21.0
[[-5.]]
[[ 40.]
 [  0.]]
104.0
[[ 120.]]
[[ 25.]
 [-20.]]
21.0
[[-5.]]
[[ 40.]
 [  0.]]
104.0
[[ 120.]]
[[ 25.]
 [-20.]]
21.0
[[-5.]]
[[ 40.]
 [  0.]]
104.0
[[ 120.]]
[[ 25.]
 [-20.]]
21.0
[[-5.]]
[[ 40.]
 [  0.]]
104.0
[[ 120.]]
[[ 25.]
 [-20.]]
21.0
[[-5.]]
[[ 40.]
 [  0.]]
104.0
[[ 120.]]
[[ 25.]
 [-20.]]
21.0
[[-5.]]
[[ 40.]
 [  0.]]
104.0
[[ 120.]]
[[ 25.]
 [-20.]]
21.0
[[-5.]]
[[ 40.]
 [  0.]]
10