In [1]:
import tensorflow as tf

Belowing code is an example of how to write tensorflow session in jupyter environment

In [2]:
interactive_sesssion=tf.InteractiveSession()

In [3]:
a=tf.Variable([[1,2,3],[4,5,6],[6,7,0]],name='a')

In [4]:
b=tf.Variable([[9,3,2],[4,6,8],[0,2,4]])

In [5]:
c=tf.matmul(a,b)

In [7]:
init_op=tf.initialize_all_variables()

In [8]:
interactive_sesssion.run(init_op)

In [9]:
print(interactive_sesssion.run(c))

[[17 21 30]
 [56 54 72]
 [82 60 68]]


In [11]:
c.get_shape()

TensorShape([Dimension(3), Dimension(3)])