In [1]:
import tensorflow as tf
import math

In [2]:
interactive_sesssion=tf.InteractiveSession()

In [21]:
y=[[5.,4.,1.],[1.,9.,20.],[3.,4.,3.]]

In [22]:
y_=[[1,0,0],[1,0,0],[1,0,0]]

In [23]:
cross_entropy=tf.nn.softmax_cross_entropy_with_logits(y,y_)

In [24]:
interactive_sesssion.run(cross_entropy)

array([  0.32656264,  19.00001717,   1.55144465], dtype=float32)

In [35]:
softmax=tf.nn.softmax(y)

In [36]:
interactive_sesssion.run(softmax)

array([[  7.21399188e-01,   2.65387923e-01,   1.32128876e-02],
       [  5.60270275e-09,   1.67014223e-05,   9.99983311e-01],
       [  2.11941570e-01,   5.76116920e-01,   2.11941570e-01]], dtype=float32)

In [38]:
-1*math.log(0.721399188)

0.3265626361024641

following is to make a deep learning model using softmax, it looks like optim don't action

In [38]:
x=tf.constant([[3.0,4.0,5.0]])

In [39]:
#weight=tf.Variable(tf.random_normal([3,1],stddev=1,seed=1))
weight=tf.Variable([[]])

In [40]:
y_=tf.constant([1.0])

In [41]:
y=tf.matmul(x,weight)

In [48]:
y_softmax=tf.nn.softmax(y)

In [49]:
#loss_function=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(model,y_))
loss_function=-tf.reduce_mean(y_*tf.log(tf.clip_by_value(y_softmax,1e-10,1.0)))

In [55]:
optim = tf.train.AdamOptimizer(0.001)

In [56]:
train_step=optim.minimize(loss_function)

In [57]:
init_op=tf.initialize_all_variables()

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [58]:
interactive_sesssion.run(init_op)

In [59]:
for i in range(100):
    interactive_sesssion.run(train_step)
    loss=interactive_sesssion.run(loss_function)
    w=interactive_sesssion.run(weight)
    print(w)
    print(loss)

[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 [ 0.3215887 ]]
-0.0
[[-0.67590594]
 [ 0.28665832]
 