In [69]:
import tensorflow as tf

In [70]:
from numpy.random import RandomState

In [71]:
batch_size=8

In [72]:
w1=tf.Variable(tf.random_normal([2,3],stddev=1,seed=1))
w2=tf.Variable(tf.random_normal([3,1],stddev=1,seed=1))

forward propagation

In [73]:
x=tf.placeholder(tf.float32,shape=(None,2),name='x-input')
y_=tf.placeholder(tf.float32,shape=(None,1),name='y-input')

In [74]:
a=tf.matmul(x,w1)
y=tf.matmul(a,w2)

back propagation

In [75]:
cross_entropy=-tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y,1e-10,1.0)))

In [76]:
train_step=tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

In [77]:
rdm=RandomState(1)

In [78]:
help(RandomState)

Help on class RandomState in module numpy.random.mtrand:

class RandomState(builtins.object)
 |  RandomState(seed=None)
 |  
 |  Container for the Mersenne Twister pseudo-random number generator.
 |  
 |  `RandomState` exposes a number of methods for generating random numbers
 |  drawn from a variety of probability distributions. In addition to the
 |  distribution-specific arguments, each method takes a keyword argument
 |  `size` that defaults to ``None``. If `size` is ``None``, then a single
 |  value is generated and returned. If `size` is an integer, then a 1-D
 |  array filled with generated values is returned. If `size` is a tuple,
 |  then an array with that shape is filled and returned.
 |  
 |  *Compatibility Guarantee*
 |  A fixed seed and a fixed series of calls to 'RandomState' methods using
 |  the same parameters will always produce the same results up to roundoff
 |  error except when the values were incorrect. Incorrect values will be
 |  fixed and the NumPy version in

In [79]:
dataset_size=128

In [80]:
X=rdm.rand(dataset_size,2)

In [81]:
Y=[[int(x1 + x2 < 1)] for (x1,x2) in X]

In [84]:
with tf.Session() as sess:
    init_op=tf.global_variables_initializer()
    sess.run(init_op)
    print(sess.run(w1))
    print(sess.run(w2))
    
    STEPS=5000
    for i in range(STEPS):
        start=(i*batch_size) % dataset_size
        end=min(start+batch_size,dataset_size)
        sess.run(train_step,feed_dict={x:X[start:end],y_:Y[start:end]})
        #print(sess.run(w1))
        #print(sess.run(w2))
        
        total_cross_entropy=sess.run(cross_entropy,feed_dict={x:X,y_:Y})
        print("After %d training step(s),cross entropy on all data is %g" %(i,total_cross_entropy))
        
    print(sess.run(w1))
    print(sess.run(w2))

[[-0.81131822  1.48459876  0.06532937]
 [-2.44270396  0.0992484   0.59122431]]
[[-0.81131822]
 [ 1.48459876]
 [ 0.06532937]]
After 0 training step(s),cross entropy on all data is 0.0674925
After 1 training step(s),cross entropy on all data is 0.0672511
After 2 training step(s),cross entropy on all data is 0.0670647
After 3 training step(s),cross entropy on all data is 0.066914
After 4 training step(s),cross entropy on all data is 0.0667947
After 5 training step(s),cross entropy on all data is 0.0666918
After 6 training step(s),cross entropy on all data is 0.0665712
After 7 training step(s),cross entropy on all data is 0.0664202
After 8 training step(s),cross entropy on all data is 0.0662492
After 9 training step(s),cross entropy on all data is 0.066075
After 10 training step(s),cross entropy on all data is 0.0659034
After 11 training step(s),cross entropy on all data is 0.0657333
After 12 training step(s),cross entropy on all data is 0.0655595
After 13 training step(s),cross entropy on